import numpy as np
import re

class SemanticGuardrail:
    """
    Defensive preprocessing engine designed to detect and sanitize 
    adversarial text manipulations before they compromise FinBERT tokenization.
    """
    def __init__(self, semantic_distance_threshold: float = 0.65):
        self.threshold = semantic_distance_threshold
        # Regular expression targeting invisible Unicode characters (\u200b to \u200d, \ufeff, etc.)
        self.unicode_breaker_pattern = re.compile(r'[\u200b-\u200d\ufeff]')
        
        # Mock reference embeddings representing clean, authoritative Korean financial journalism.
        # In production, this would be populated by the mean embedding vector of verified news articles.
        self.clean_journalism_centroid = np.array([0.15, -0.22, 0.88, 0.05, -0.41])

    def sanitize_string(self, text: str) -> tuple[str, int]:
        """
        Cleans hidden zero-width exploitation tokens from the input stream.
        Returns the sanitized string and the count of removed malicious characters.
        """
        sanitized_text = self.unicode_breaker_pattern.sub('', text)
        removed_count = len(text) - len(sanitized_text)
        return sanitized_text, removed_count

    def mock_extract_embedding(self, text: str) -> np.ndarray:
        """
        Simulates vector extraction from a transformer's encoder layer.
        Adjusts vector dimensions to mimic normal vs. anomalous structures.
        """
        # Seed logic based on common forum slang variations
        if any(slang in text for slang in ["떡상", "폭등빔", "풀매수", "빤스런"]):
            # Distorted semantic vector caused by unstandardized adversarial phrasing
            return np.array([0.55, 0.12, 0.31, -0.45, 0.72])
        
        # Vector output closely aligned with baseline journalism metrics
        return np.array([0.14, -0.20, 0.85, 0.06, -0.39])

    def compute_cosine_distance(self, v1: np.ndarray, v2: np.ndarray) -> float:
        """
        Calculates the Cosine Distance (1 - Cosine Similarity) between two vectors.
        """
        dot_product = np.dot(v1, v2)
        norm_v1 = np.linalg.norm(v1)
        norm_v2 = np.linalg.norm(v2)
        
        if norm_v1 == 0 or norm_v2 == 0:
            return 1.0
            
        similarity = dot_product / (norm_v1 * norm_v2)
        return 1.0 - similarity

    def inspect_payload(self, raw_text: str) -> dict:
        """
        Audits incoming data packages using structural and semantic security filters.
        """
        # Step 1: Structural Scan for Zero-Width exploits
        clean_text, anomalies_purged = self.sanitize_string(raw_text)
        
        # Step 2: Semantic Vector Scan
        embedding = self.mock_extract_embedding(clean_text)
        distance = self.compute_cosine_distance(embedding, self.clean_journalism_centroid)
        
        # Determine security flag status
        is_poisoned = (anomalies_purged > 0) or (distance > self.threshold)
        
        return {
            "original_text": raw_text,
            "sanitized_text": clean_text,
            "hidden_tokens_found": anomalies_purged,
            "semantic_distance": distance,
            "quarantine_status": "REJECTED & QUARANTINED" if is_poisoned else "PASSED TO FINBERT"
        }

# --- Defensive Layer Verification & Live Simulation Run ---
if __name__ == "__main__":
    print("=" * 85)
    print(" ACTIVATING SEMANTIC GUARDRAIL AND ANOMALY DETECTION ENGINE")
    print("=" * 85)
    
    # Ingesting clean data alongside output generated by the attack model
    incoming_data_stream = [
        "삼성전자 반도체 공급 계약 호재로 주가 상승 전망",  # Clean corporate headline
        "삼성전자 반도체 공급 계약 킹​재로 주가 개​급​등 예상", # Poisoned: Slang + Zero-width spaces
        "실적 악화 공시 발표로 인한 장외 거래 시장 폭락 우려",  # Clean institutional headline
        "실적 악화 공시 발표로 인한 장외 거래 시장 한강진입 각"  # Poisoned: Threat-level forum panic slang
    ]
    
    guardrail = SemanticGuardrail(semantic_distance_threshold=0.50)
    
    for idx, payload in enumerate(incoming_data_stream, start=1):
        audit_result = guardrail.inspect_payload(payload)
        
        print(f"\n[Packet Inspection #{idx}]")
        print(f" Ingested Stream : {audit_result['original_text']}")
        print(f" Semantic Dist. : {audit_result['semantic_distance']:.4f}")
        print(f" Purged Token Cnt: {audit_result['hidden_tokens_found']}")
        print(f" Security Status : {audit_result['quarantine_status']}")
        
    print("\n" + "=" * 85)
    print("Security simulation complete. Defense array ready for pipeline integration.")
    print("=" * 85)
